# Generated by Django 4.0.3 on 2022-04-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0002_alter_equipo_empatados_alter_equipo_ganados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('nick', models.CharField(max_length=30, verbose_name='Apodo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='equipos.equipo', verbose_name='Equipo')),
            ],
        ),
    ]
