# Generated by Django 4.0.3 on 2022-04-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['nick'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
    ]
