# Generated by Django 4.0.3 on 2022-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_empatados_alter_equipo_ganados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['conferencia', 'division'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='conferencia',
            field=models.CharField(choices=[('AFC', 'American'), ('NFC', 'National')], default='NFC', max_length=8, verbose_name='Conferencia'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='division',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('South', 'South'), ('North', 'North')], default='East', max_length=5, verbose_name='Div'),
        ),
    ]
