# Generated by Django 4.0.3 on 2022-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_equipo_options_equipo_conferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Logo'),
        ),
    ]
