# Generated by Django 4.0.3 on 2022-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_alter_equipo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='img/equipo', verbose_name='Logo'),
        ),
    ]
